2013-03-20 01:23:02 Error: [PDOException] SQLSTATE[42712]: Duplicate alias: 7 ERROR:  el nombre de tabla «Category» fue especificado más de una vez
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Model\Datasource\DboSource.php(459): PDOStatement->execute(Array)
#1 C:\xampp\cakephp-2.2.3\lib\Cake\Model\Datasource\DboSource.php(425): DboSource->_execute('SELECT "Categor...', Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Model\Datasource\DboSource.php(669): DboSource->execute('SELECT "Categor...', Array, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Model\Datasource\DboSource.php(1080): DboSource->fetchAll('SELECT "Categor...', false)
#4 C:\xampp\cakephp-2.2.3\lib\Cake\Model\Model.php(2630): DboSource->read(Object(Category), Array)
#5 C:\xampp\cakephp-2.2.3\lib\Cake\Controller\Component\PaginatorComponent.php(173): Model->find('all', Array)
#6 C:\xampp\cakephp-2.2.3\lib\Cake\Controller\Controller.php(1081): PaginatorComponent->paginate(NULL, Array, Array)
#7 D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php(17): Controller->paginate()
#8 [internal function]: CategoriesController->index()
#9 C:\xampp\cakephp-2.2.3\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(CategoriesController), Array)
#10 C:\xampp\cakephp-2.2.3\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\cakephp-2.2.3\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(CategoriesController), Object(CakeRequest), Object(CakeResponse))
#12 D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\webroot\index.php(97): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2013-03-20 01:23:46 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:23:46 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:24:09 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:24:09 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:24:22 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:24:22 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:25:31 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:25:31 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:25:32 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:25:32 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:25:32 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:25:32 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:25:32 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:25:32 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:25:32 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:25:32 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:25:33 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:25:33 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:25:33 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:25:33 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:25:33 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:25:33 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:25:33 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:25:33 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:25:33 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:25:33 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:26:53 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\CategoriesController.php, line 50]
2013-03-20 01:26:53 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-20 01:30:28 Error: [PDOException] SQLSTATE[42712]: Duplicate alias: 7 ERROR:  el nombre de tabla «Item» fue especificado más de una vez
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Model\Datasource\DboSource.php(459): PDOStatement->execute(Array)
#1 C:\xampp\cakephp-2.2.3\lib\Cake\Model\Datasource\DboSource.php(425): DboSource->_execute('SELECT "Item"."...', Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Model\Datasource\DboSource.php(669): DboSource->execute('SELECT "Item"."...', Array, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Model\Datasource\DboSource.php(1080): DboSource->fetchAll('SELECT "Item"."...', false)
#4 C:\xampp\cakephp-2.2.3\lib\Cake\Model\Model.php(2630): DboSource->read(Object(Item), Array)
#5 C:\xampp\cakephp-2.2.3\lib\Cake\Controller\Component\PaginatorComponent.php(173): Model->find('all', Array)
#6 C:\xampp\cakephp-2.2.3\lib\Cake\Controller\Controller.php(1081): PaginatorComponent->paginate(NULL, Array, Array)
#7 D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\ItemsController.php(17): Controller->paginate()
#8 [internal function]: ItemsController->index()
#9 C:\xampp\cakephp-2.2.3\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(ItemsController), Array)
#10 C:\xampp\cakephp-2.2.3\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\cakephp-2.2.3\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(ItemsController), Object(CakeRequest), Object(CakeResponse))
#12 D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\webroot\index.php(97): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2013-03-20 01:31:11 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\elvis.caceres\Dropbox\My projects\scaideasoft\src\Controller\ItemsController.php, line 50]
2013-03-20 01:31:11 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\cakephp-2.2.3\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#2 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\elvis.cacere...', 50, Array)
#3 C:\xampp\cakephp-2.2.3\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
